### ISSUE TITLE
您好，运行您的代码出现：ModuleNotFoundError: No module named 'dynaconf'：

### ISSUE THREAD

**Issue by xizhulove** [neardws/Incentive-based-Probability-Update-and-Strategy-Selection#2]

**Comment by neardws** [comment]
你的邮件已收到，谢谢！

**Comment by xizhulove** [comment]
@neardws config里面的from dynaconf import Dynaconf 这里有问题，可以提供一份完整的代码吗？想学习一下感谢

**Comment by neardws** [comment]
你好，你可以通过`pip install dynaconf`进行安装，具体可参看：[https://github.com/rochacbruno/dynaconf](https://github.com/rochacbruno/dynaconf)

**Comment by xizhulove** [comment]
好的，谢谢，我装完那个包之后现在报错了&nbsp; &nbsp;&nbsp;
np_array1 = generator_of_strategy_selection_probability(np.power(6, 10))
NameError: name 'generator_of_strategy_selection_probability' is not defined

您知道怎么解决吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neardws/Incentive-based-Probability-Update-and-Strategy-Selection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neardws/Incentive-based-Probability-Update-and-Strategy-Selection] 您好，运行您的代码出现：ModuleNotFoundError: No module named 'dynaconf'： (Issue #2)





 
你好，你可以通过pip install dynaconf进行安装，具体可参看：https://github.com/rochacbruno/dynaconf

**Comment by xizhulove** [comment]
我这边运行这个代码还有挺多报错的，您那边方便提供一下完整的代码吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neardws/Incentive-based-Probability-Update-and-Strategy-Selection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neardws/Incentive-based-Probability-Update-and-Strategy-Selection] 您好，运行您的代码出现：ModuleNotFoundError: No module named 'dynaconf'： (Issue #2)





 
你好，你可以通过pip install dynaconf进行安装，具体可参看：https://github.com/rochacbruno/dynaconf

**Comment by neardws** [comment]
> 我这边运行这个代码还有挺多报错的，您那边方便提供一下完整的代码吗
> […](#)

GitHub 上的就是完整代码，当它迁移到其他机器上，由于环境等因素难免会出现问题，如果你希望复现我的代码，我建议你可以直接参考 algorithm 文件夹内的代码内容。

**Comment by xizhulove** [comment]
好的，非常感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neardws/Incentive-based-Probability-Update-and-Strategy-Selection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neardws/Incentive-based-Probability-Update-and-Strategy-Selection] 您好，运行您的代码出现：ModuleNotFoundError: No module named 'dynaconf'： (Issue #2)





  
我这边运行这个代码还有挺多报错的，您那边方便提供一下完整的代码吗
 …
  
GitHub 上的就是完整代码，当它迁移到其他机器上，由于环境等因素难免会出现问题，如果你希望复现我的代码，我建议你可以直接参考 algorithm 文件夹内的代码内容。
